export const FETCH_STATISTICS = 'FETCH_STATISTICS'; 
export const SET_PLAYERS = 'SET_PLAYERS';
export const RESET_STATISTICS = 'RESET_STATISTICS';
export const PLAY_GAME = 'PLAY_GAME';
export const RESET_GAME = 'RESET_GAME';